# Generated by Django 4.2.7 on 2026-03-14 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychallengeattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='participants',
            field=models.ManyToManyField(related_name='daily_challenges', through='challenges.DailyChallengeAttempt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
        migrations.AlterUniqueTogether(
            name='dailychallengeattempt',
            unique_together={('challenge', 'user')},
        ),
    ]
