# Generated by Django 4.2.7 on 2026-03-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quizzes_taken', models.IntegerField(default=0)),
                ('questions_answered', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TopicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('avg_time_seconds', models.FloatField(default=0.0)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'topic_performances',
                'ordering': ['-total_questions'],
            },
        ),
    ]
